In [1]:
import numpy as np

Scalar - 0 dimensiones

In [2]:
scalar = np.array(42)
scalar

array(42)

In [3]:
scalar.ndim

0

Vector - 1 dimensión ó arreglo unidimensional

In [4]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [5]:
vector.ndim

1

Matriz - 2 dimensiones

In [7]:
matriz = np.array([[1,2,3], [4,5,6]])
print(matriz, matriz.ndim)

[[1 2 3]
 [4 5 6]] 2


Tensor - n dimensiones

In [9]:
tensor = np.array([[[[[[[[[1]]]]]]]]])
tensor

array([[[[[[[[[1]]]]]]]]])

In [10]:
tensor.ndim

9