In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
arr.dtype

dtype('int64')

In [4]:
arr_float = np.array([1,2,3,4], dtype="float64")
arr_float

array([1., 2., 3., 4.])

In [6]:
arr1 = np.array([1,"holaaa",3,"4"])
arr1

array(['1', 'holaaa', '3', '4'], dtype='<U21')

Cambiar el tipo de dato de un array

In [8]:
arr = np.array([0, 1, 2, 3, 4])
arr_bool = arr.astype(np.bool_)
arr_bool

array([False,  True,  True,  True,  True])

In [10]:

arr_string = arr.astype(np.string_)
arr_string

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')