In [12]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Zeros

In [18]:
np.zeros(shape=(3,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [19]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Ones

In [20]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Linspace

In [26]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

Eye

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random

In [32]:
np.random.rand()

0.29336991920838407

In [33]:
np.random.rand(3)

array([0.61624814, 0.12010003, 0.74812801])

In [34]:
np.random.rand(4,4)

array([[0.53428066, 0.24623262, 0.84642335, 0.01446848],
       [0.93742795, 0.54269712, 0.84454232, 0.23157835],
       [0.15894788, 0.3184307 , 0.00465652, 0.82279067],
       [0.2432865 , 0.17305299, 0.43014646, 0.9210327 ]])

In [53]:
np.random.randint(1,100)

53

In [40]:
np.random.randint(1,100, (10,10))

array([[15, 58, 39,  6, 45, 49, 48, 68, 63, 37],
       [99, 55, 97, 90, 14,  4, 96, 95, 34, 71],
       [39, 26, 91, 10,  2,  3, 63, 50, 39, 78],
       [ 5, 45, 46, 61, 49, 87, 73, 13, 24, 58],
       [73, 74,  6, 78, 46, 32, 65, 43, 85, 71],
       [55, 21, 46, 44, 14, 27, 57, 45, 67, 18],
       [ 2, 21, 29,  2, 21, 66, 17, 77, 57, 54],
       [69, 70, 58, 30, 11, 52, 65, 33, 26, 86],
       [45, 81, 22, 65, 71, 63, 74, 88, 26, 34],
       [83, 53, 26, 32, 33, 44, 26, 56, 47, 36]])