In [1]:
import numpy as np

In [29]:
#arr = np.random.randint(1, 20, 10)

#random.randint(low, high=None, size=None, dtype=int)
arr = np.random.randint(low=1, high=20, size=10)
arr

array([ 7, 10,  3, 16,  5,  4, 15, 19,  8, 14])

In [30]:
matriz = arr.reshape(2,5)
matriz

array([[ 7, 10,  3, 16,  5],
       [ 4, 15, 19,  8, 14]])

Max y Argmax

In [31]:
arr.max()

19

In [32]:
matriz.max()

19

In [33]:
# Obtiene el índice del elemento mayor
# https://numpy.org/doc/stable/reference/generated/numpy.argmax.html#numpy-argmax
arr.argmax()

7

Min y Argmin

In [34]:
arr.min()

3

In [35]:
# Obtiene el índice del elemento menor
# https://numpy.org/doc/stable/reference/generated/numpy.argmin.html
arr.argmin()

2

In [38]:
matriz.min(0)

array([ 4, 10,  3,  8,  5])

In [41]:
matriz

array([[ 7, 10,  3, 16,  5],
       [ 4, 15, 19,  8, 14]])

In [45]:
# Comparación entre los elementos de la D1
# Compara estos elementos:
# 0: [ 7, 10,  3, 16,  5]
# 1: [ 4, 15, 19,  8, 14]
#    [ 1,  0,  0,  1, 0]

matriz.argmin(0)

array([1, 0, 0, 1, 0])

In [46]:
# Comparación entre los elementos de la D2
# [ 7, 10,  3, 16,  5]
#           *
#   0   1   2   3   4 => 2
# [ 4, 15, 19,  8, 14]
#   *
#   0   1   2   3   4 => 0

matriz.argmin(1)

array([2, 0])

**PTP** (Peak to Peak)

La resta entre el máximo y el mínimo.
https://numpy.org/doc/2.0/reference/generated/numpy.ptp.html


In [47]:
arr

array([ 7, 10,  3, 16,  5,  4, 15, 19,  8, 14])

In [51]:
print(f"max: {arr.max()} - min: {arr.min()} = {arr.ptp()}")

max: 19 - min: 3 = 16


In [49]:
arr.ptp()

16

Sort

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [52]:
arr

array([ 7, 10,  3, 16,  5,  4, 15, 19,  8, 14])

In [54]:
arr.sort()
arr

array([ 3,  4,  5,  7,  8, 10, 14, 15, 16, 19])

Media/Mean

In [55]:
np.mean(arr)

10.1

Mediana/median

In [56]:
np.median(arr)

9.0

Percentil

In [57]:
np.percentile(arr,50)

9.0

Varianza

In [58]:
np.var(arr)

28.089999999999996

Desviación Estándar

In [59]:
np.std(arr)

5.3