In [1]:
import numpy as np

In [4]:
arr = np.arange(1,11)
arr
#   0   1   2   3   4   5   6   7   8   9
# [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Filtrado por condiciones

In [6]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
#   0   1   2   3   4   5   6   7   8   9
# [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]

In [13]:
arr[1]

2

In [10]:
#   *   *       *
#   0   1   2   3   4   5   6   7   8   9
# [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]

arr[np.array([0,1,3])]

array([1, 2, 4])

In [15]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10])

In [16]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [17]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8])

In [18]:
arr[arr>5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99])