In [1]:
import numpy as np

In [7]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Slicing
sub_arr = arr[0:6]
sub_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
sub_arr[:] = 0
sub_arr

array([0, 0, 0, 0, 0, 0])

In [10]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Copy

In [11]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [12]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [13]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])