In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [4]:
lista ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [32]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
1/arr

<ipython-input-36-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [37]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Operaciones entre arrays

In [38]:
arr2 = arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
arr - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Operaciones con matrices

In [43]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
matriz1 = matriz.copy()

In [45]:
matriz + matriz1

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [46]:
matriz - matriz1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [47]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
matriz1.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [49]:
# A(mxn) * B(nxp) = C(mxp)
np.matmul(matriz, matriz1.T)

array([[ 30,  80],
       [ 80, 255]])

In [50]:
matriz @ matriz1.T

array([[ 30,  80],
       [ 80, 255]])